CI: python 3.12-dev
MagicStack/uvloop pull request #555
Opened 2023-08-12 02:17 UTC by dulmandakh

2023-10-02 17:57 UTC, michael-k commented
Is there a way forward/a way to unblock this?  Is MagicStack/uvloop#534 enough to unblock this?

2023-10-05 11:04 UTC, tarsil commented
By the time of this writing, 3.0.3 was merged and a release is being prepared https://github.com/cython/cython/actions/runs/6417571100

Maybe we can finally move on :)

2023-10-05 18:18 UTC, josecsotomorales requested changes

2023-10-05 18:18 UTC, josecsotomorales commented on .github/workflows/tests.yml
> +        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-dev"]
We should use `3.12` instead of `3.12-dev`

2023-10-06 21:57 UTC, tarsil commented
This PR is in draft mode. Maybe someone needs to create another one with the official move to python 3.12 and also take care of this 

https://github.com/MagicStack/uvloop/issues/568

2023-10-15 16:43 UTC, fantix commented
Yeah, thank you for the PR! Closing because #570 is merged.

2023-10-15 16:43 UTC, closed without merging